version: "3.3"

services:
  app:
    build: .
    container_name: yt-organizer-app
    restart: always
    volumes:
      - ./static:/static
    expose:
      - "8000"
    command: "/start_app.sh"

  app-static:
    image: nginx:latest
    container_name: yt-organizer-app-static
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - app
