version: "3.3"

services:
  app:
    build: .
    container_name: yt-organizer-app
    restart: always
    ports:
      - "8000:8000"
    command: "gunicorn --workers=2 --bind=0.0.0.0:8000 yt_organizer.wsgi:application"
