version: "3.3"

services:
  app:
    build: .
    container_name: yt-organizer-app
    restart: always
    volumes:
      - static_data:/static
    expose:
      - "8000"
    depends_on:
      - app-db
    env_file:
      - .env
    command: "/start_app.sh"

  app-static:
    image: nginx:latest
    container_name: yt-organizer-app-static
    volumes:
      - static_data:/usr/share/nginx/html
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - app

  app-db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
  static_data: