# Generated by Django 3.0.7 on 2020-06-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0003_auto_20200624_1903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video", name="published_date", field=models.DateTimeField(),
        ),
    ]
